### ISSUE TITLE
Automatically replace ambiguous bases with N

### ISSUE THREAD

**Issue by milesroberts-123** [harvardinformatics/degenotate#15]
Thank you so much for the work you put into this awesome tool! I gave degenotate a go and noticed that the presence of ambiguous bases (R, M, Y, W, etc.) in coding sequences will throw an error.

This is pretty easy to fix by replacing ambiguous bases with "N" in the genome fasta file before running degenotate. I did it using regular expressions in [seqkit](https://bioinf.shenwei.me/seqkit/), for example:

`seqkit replace -s -p [^ATGC] -r N genome.fa  > genome_noAmbig.fa`

However, I think it would be cool to have degenotate do this automatically. I am hoping that would be relatively straightforward to implement, since I'm assuming degenotate is already looping over individual codons.

Anyway, just a suggestion!

**Comment by gwct** [comment]
Hey!
Thanks for pointing this out. We actually also just noticed this too and have pushed a fix on the [develop branch](https://github.com/harvardinformatics/degenotate/tree/develop) so that any codons with ambiguous nucleotides are skipped. We'll pull that branch into main in a few days since we're still working on some other stuff, but feel free to download that branch and let us know if it works!
-Gregg

**Comment by tsackton** [comment]
The fix for this issue is now pushed to main, but won't make it to conda for a bit as we have a few other bugs to fix before issuing a new release. Thanks for testing this out, and if you find any other issues please let us know!

**Comment by tsackton** [comment]
Closed by #14

**Comment by milesroberts-123** [comment]
Wonderful! Thank you so much for your quick response!
